language: cpp
notifications:
  email: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-9 main'
        key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
      - boost-latest
    packages:
      - gcc-9
      - g++-9
      - clang-9
      - libboost-date-time1.58.0
      - libboost-date-time1.58-dev
      - libboost-filesystem1.58.0
      - libboost-filesystem1.58-dev
      - libboost-locale1.58.0
      - libboost-locale1.58-dev
      - libboost-program-options1.58.0
      - libboost-program-options1.58-dev
      - libboost-system1.58.0
      - libboost-system1.58-dev
  coverity_scan:
    project:
      name: "mikedld/bt-migrate"
      description: "Build submitted via Travis CI"
    notification_email: mikedld@mikedld.com
    build_command_prepend: if [ "$TRAVIS_OS_NAME" = linux -a "$CC" = gcc ]; then cmake .. -DCMAKE_BUILD_TYPE=Debug; fi
    build_command: make
    branch_pattern: coverity_scan
sudo: false
before_script:
  - |
    if [ "$TRAVIS_OS_NAME" = linux ]; then
      set -e

      mkdir bin
      ln -s /usr/bin/gcc-9 bin/gcc
      ln -s /usr/bin/g++-9 bin/g++
      ln -s /usr/bin/clang-9 bin/clang
      ln -s /usr/bin/clang++-9 bin/clang++
      export PATH=$PWD/bin:$PATH

      wget --no-check-certificate https://cmake.org/files/v3.16/cmake-3.16.1-Linux-x86_64.tar.gz -O /tmp/cmake.tar.gz
      tar xf /tmp/cmake.tar.gz
      export PATH=$PWD/cmake-3.16.1-Linux-x86_64/bin:$PATH

      set +e
    fi
  - mkdir obj
  - cd obj
script:
  - |
    if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then
      cmake .. -DCMAKE_BUILD_TYPE=Release
      make -j2
    fi
matrix:
  include:
    - os: linux
      compiler: gcc
    - os: linux
      compiler: clang
    - os: osx
      compiler: clang
      osx_image: xcode11.2
      install:
        - brew update
        - brew install cmake || brew upgrade cmake || true
